# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: malexand <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/07/23 09:22:02 by malexand          #+#    #+#              #
#    Updated: 2015/07/24 11:02:08 by malexand         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = srcs/ft_display_file.c
LIB = libft.a

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRCS) $(LIB)
clean:
	rm -rf $(SRCO)
fclean: clean
	rm -rf $(NAME)
